# Generated by Django 4.0.7 on 2022-10-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=255, verbose_name='Problema')),
                ('descricao', models.TextField(verbose_name='Descrição do problema')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_abertura', models.DateTimeField(null=True)),
                ('data_fechamento', models.DateTimeField(null=True)),
                ('tempo_manutencao', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('S', 'Solicitado'), ('A', 'Aberto'), ('F', 'Fechado')], default='S', max_length=1)),
                ('pessoa_solicitante', models.CharField(max_length=255)),
                ('custo_manutencao', models.DecimalField(decimal_places=2, default=0, max_digits=25, null=True)),
            ],
            options={
                'verbose_name': 'Chamados',
            },
        ),
    ]
