# Generated by Django 4.0.7 on 2022-10-28 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_coordenador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to=settings.AUTH_USER_MODEL),
        ),
    ]
