# Generated by Django 4.0.7 on 2022-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_coordenador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_profissional',
            field=models.CharField(choices=[(1, 'Coordenador de Engenharia Clínica'), (2, 'Técnico Hospitalar'), (3, 'Profissional de saúde')], default=3, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Coordenador',
        ),
    ]
